[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$utf8 = New-Object System.Text.UTF8Encoding($false)
$filePath = "$(Get-Location)\app\page.js"

$content = [System.IO.File]::ReadAllText($filePath, $utf8)

# Construct mangled strings using precise character code sequences (100% ASCII source)
$mangled_memo = [string][char[]]@(240, 376, 8220, 157)
$mangled_date = [string][char[]]@(240, 376, 8220, 8230)
$mangled_camera = [string][char[]]@(240, 376, 8220, 183)
$mangled_pdf = [string][char[]]@(240, 376, 8220, 8222)
$mangled_wa = [string][char[]]@(240, 376, 8217, 172)
$mangled_trash = [string][char[]]@(240, 376, 8212, 8216, 239, 184, 143)
$mangled_offline = [string][char[]]@(226, 353, 160, 239, 184, 143)

# Helper to construct Emojis using ConvertFromUtf32
function getEmoji([int]$code) {
    return [char]::ConvertFromUtf32($code)
}

# 1. Replace all mangled emoji buttons and headers
$content = $content.Replace(($mangled_memo + ' New DPR'), '&#128221; New DPR')
$content = $content.Replace(($mangled_memo + '  New DPR'), '&#128221; New DPR')
$content = $content.Replace(($mangled_memo + ' History'), '&#128221; History')
$content = $content.Replace(($mangled_memo + '  History'), '&#128221; History')
$content = $content.Replace(($mangled_date + ' Date &amp; Site'), '&#128197; Date &amp; Site')
$content = $content.Replace(($mangled_date + '  Date &amp; Site'), '&#128197; Date &amp; Site')
$content = $content.Replace(($mangled_camera + ' Download Image'), '&#128317; Download Image')
$content = $content.Replace(($mangled_camera + '  Download Image'), '&#128317; Download Image')
$content = $content.Replace(($mangled_pdf + ' Download PDF'), '&#128317; Download PDF')
$content = $content.Replace(($mangled_pdf + '  Download PDF'), '&#128317; Download PDF')
$content = $content.Replace(($mangled_wa + ' Copy for WhatsApp'), '&#128172; Copy for WhatsApp')
$content = $content.Replace(($mangled_wa + '  Copy for WhatsApp'), '&#128172; Copy for WhatsApp')
$content = $content.Replace(($mangled_memo + ' DPR History'), '&#128221; DPR History')
$content = $content.Replace(($mangled_memo + '  DPR History'), '&#128221; DPR History')
$content = $content.Replace($mangled_trash, '&#128465;&#65039;')
$content = $content.Replace(($mangled_offline + ' Offline Mode'), '&#9888;&#65039; Offline Mode')
$content = $content.Replace(($mangled_offline + '  Offline Mode'), '&#9888;&#65039; Offline Mode')

# 2. Replace raw layout emojis in JSX code with safe HTML entities
$content = $content.Replace(((getEmoji 0x1F4CA) + ' Dashboard'), '&#128202; Dashboard')
$content = $content.Replace((([char]0x2699 + [char]0xFE0F) + ' Admin'), '&#9881;&#65039; Admin')
$content = $content.Replace(((getEmoji 0x1F4CB) + ' Work Activities'), '&#128203; Work Activities')
$content = $content.Replace(([char]0x2705 + ' Generate DPR'), '&#9989; Generate DPR')
$content = $content.Replace(((getEmoji 0x1F4CA) + ' Summary Dashboard'), '&#128202; Summary Dashboard')
$content = $content.Replace(((getEmoji 0x1F4CD) + ' Site-wise Manpower'), '&#128205; Site-wise Manpower')
$content = $content.Replace(((getEmoji 0x1F4CA) + ' Admin Analytics Dashboard'), '&#128202; Admin Analytics Dashboard')
$content = $content.Replace(((getEmoji 0x1F4E5) + ' Export Master Log (CSV)'), '&#128317; Export Master Log (CSV)')
$content = $content.Replace((([char]0x270F + [char]0xFE0F) + ' Pending Edit Requests'), '&#9999;&#65039; Pending Edit Requests')
$content = $content.Replace(([char]0x2705 + ' No pending requests.'), '&#9989; No pending requests.')
$content = $content.Replace(((getEmoji 0x1F9F9) + ' Clean Corrupted Rows'), '&#129529; Clean Corrupted Rows')
$content = $content.Replace((([char]0x2699 + [char]0xFE0F) + ' Create / Manage Users'), '&#9881;&#65039; Create / Manage Users')
$content = $content.Replace(([char]0x2795 + ' Create New User'), '&#10133; Create New User')
$content = $content.Replace(([char]0x2705 + ' Create User'), '&#9989; Create User')
$content = $content.Replace(((getEmoji 0x1F465) + ' All Users'), '&#128101; All Users')
$content = $content.Replace(((getEmoji 0x1F4CD) + ' Manage Projects &amp; Sub-Projects'), '&#128205; Manage Projects &amp; Sub-Projects')
$content = $content.Replace(([char]0x2795 + ' Add Project'), '&#10133; Add Project')
$content = $content.Replace(([char]0x2705 + ' Add Project'), '&#9989; Add Project')
$content = $content.Replace(((getEmoji 0x1F4CB) + ' All Projects'), '&#128203; All Projects')
$content = $content.Replace(((getEmoji 0x1F4CB) + ' Manage Activities &amp; Sub-Activities'), '&#128203; Manage Activities &amp; Sub-Activities')
$content = $content.Replace(([char]0x2795 + ' Add Main Activity'), '&#10133; Add Main Activity')
$content = $content.Replace(([char]0x2705 + ' Add Category'), '&#9989; Add Category')
$content = $content.Replace(([char]0x2795 + ' Add Sub-Activity'), '&#10133; Add Sub-Activity')
$content = $content.Replace(([char]0x2705 + ' Add Sub-Activity'), '&#9989; Add Sub-Activity')
$content = $content.Replace(((getEmoji 0x1F4CA) + ' All Activities'), '&#128202; All Activities')
$content = $content.Replace(((getEmoji 0x1F4CA) + ' DPR ' + [char]0x2014 + ' Man Power Report'), '&#128202; DPR &mdash; Man Power Report')
$content = $content.Replace(((getEmoji 0x1F4CB) + ' DPR ' + [char]0x2014 + ' Man Power Report'), '&#128203; DPR &mdash; Man Power Report')
$content = $content.Replace(((getEmoji 0x1F4CB) + ' MAN POWER REPORT'), '&#128203; MAN POWER REPORT')

# 3. Replace raw arrows/triangles in JSX and JS Code with standard HTML entities and Unicode escapes
$content = $content.Replace(('icon.textContent = body.classList.contains(''open'') ? ''' + [char]0x25BC + ''' : ''' + [char]0x25B6 + ''';'), 'icon.textContent = body.classList.contains(''open'') ? ''\u25BC'' : ''\u25B6'';')
$content = $content.Replace(('<span className="aci admin-acc-icon">' + [char]0x25B6 + '</span>'), '<span className="aci admin-acc-icon">&#9654;</span>')
$content = $content.Replace(('<span className="aci admin-acc-icon">' + [char]0x25BC + '</span>'), '<span className="aci admin-acc-icon">&#9660;</span>')
$content = $content.Replace(([char]0x25C0 + ' Previous'), '&#9664; Previous')
$content = $content.Replace(('Next ' + [char]0x25B6), 'Next &#9654;')

# 4. Replace raw emojis in JavaScript strings with standard Unicode JS escapes to prevent mangling
$content = $content.Replace(([char]0x23F3 + ' Loading data...'), '\u23F3 Loading data...')
$content = $content.Replace(([char]0x23F3 + ' Authenticating...'), '\u23F3 Authenticating...')
$content = $content.Replace(([char]0x23F3 + ' Signing in...'), '\u23F3 Signing in...')
$content = $content.Replace(([char]0x23F3 + ' Deleting...'), '\u23F3 Deleting...')
$content = $content.Replace(([char]0x23F3 + ' Approving...'), '\u23F3 Approving...')
$content = $content.Replace(([char]0x23F3 + ' Loading...'), '\u23F3 Loading...')
$content = $content.Replace(([char]0x23F3 + ' Edit Pending'), '\u23F3 Edit Pending')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Failed to load records.'), '\u26A0\uFE0F Failed to load records.')
$content = $content.Replace(([char]0x26A0 + ' Failed to load records.'), '\u26A0\uFE0F Failed to load records.')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Could not reach server'), '\u26A0\uFE0F Could not reach server')
$content = $content.Replace(([char]0x26A0 + ' Could not reach server'), '\u26A0\uFE0F Could not reach server')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Connection error. Try again.'), '\u26A0\uFE0F Connection error. Try again.')
$content = $content.Replace(([char]0x26A0 + ' Connection error. Try again.'), '\u26A0\uFE0F Connection error. Try again.')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Connection error. Check your internet.'), '\u26A0\uFE0F Connection error. Check your internet.')
$content = $content.Replace(([char]0x26A0 + ' Connection error. Check your internet.'), '\u26A0\uFE0F Connection error. Check your internet.')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Delete failed'), '\u26A0\uFE0F Delete failed')
$content = $content.Replace(([char]0x26A0 + ' Delete failed'), '\u26A0\uFE0F Delete failed')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Please sign in first'), '\u26A0\uFE0F Please sign in first')
$content = $content.Replace(([char]0x26A0 + ' Please sign in first'), '\u26A0\uFE0F Please sign in first')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Select a date'), '\u26A0\uFE0F Select a date')
$content = $content.Replace(([char]0x26A0 + ' Select a date'), '\u26A0\uFE0F Select a date')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Select a site'), '\u26A0\uFE0F Select a site')
$content = $content.Replace(([char]0x26A0 + ' Select a site'), '\u26A0\uFE0F Select a site')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Enter at least one activity with workers'), '\u26A0\uFE0F Enter at least one activity with workers')
$content = $content.Replace(([char]0x26A0 + ' Enter at least one activity with workers'), '\u26A0\uFE0F Enter at least one activity with workers')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Save failed ' + [char]0x2014 + ' check connection'), '\u26A0\uFE0F Save failed \u2014 check connection')
$content = $content.Replace(([char]0x26A0 + ' Save failed ' + [char]0x2014 + ' check connection'), '\u26A0\uFE0F Save failed \u2014 check connection')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Sync failed'), '\u26A0\uFE0F Sync failed')
$content = $content.Replace(([char]0x26A0 + ' Sync failed'), '\u26A0\uFE0F Sync failed')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' No history records to export'), '\u26A0\uFE0F No history records to export')
$content = $content.Replace(([char]0x26A0 + ' No history records to export'), '\u26A0\uFE0F No history records to export')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Error: '), '\u26A0\uFE0F Error: ')
$content = $content.Replace(([char]0x26A0 + ' Error: '), '\u26A0\uFE0F Error: ')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Generate DPR first'), '\u26A0\uFE0F Generate DPR first')
$content = $content.Replace(([char]0x26A0 + ' Generate DPR first'), '\u26A0\uFE0F Generate DPR first')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Image generation failed'), '\u26A0\uFE0F Image generation failed')
$content = $content.Replace(([char]0x26A0 + ' Image generation failed'), '\u26A0\uFE0F Image generation failed')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' PDF generation failed'), '\u26A0\uFE0F PDF generation failed')
$content = $content.Replace(([char]0x26A0 + ' PDF generation failed'), '\u26A0\uFE0F PDF generation failed')
$content = $content.Replace(([char]0x26A0 + [char]0xFE0F + ' Inactive'), '\u26A0\uFE0F Inactive')
$content = $content.Replace(([char]0x26A0 + ' Inactive'), '\u26A0\uFE0F Inactive')
$content = $content.Replace(([char]0x274C + ' Enter username and password.'), '\u274C Enter username and password.')
$content = $content.Replace(([char]0x274C + ' Invalid username or password.'), '\u274C Invalid username or password.')
$content = $content.Replace(([char]0x274C + ' Only Admin can delete'), '\u274C Only Admin can delete')
$content = $content.Replace(([char]0x274C + ' You can only edit your own DPRs'), '\u274C You can only edit your own DPRs')
$content = $content.Replace(([char]0x274C + ' Network error: '), '\u274C Network error: ')
$content = $content.Replace(([char]0x2705 + ' CSV Exported!'), '\u2705 CSV Exported!')
$content = $content.Replace(([char]0x274C + ' Clear Filter'), '\u274C Clear Filter')
$content = $content.Replace(([char]0x2705 + ' Saved!'), '\u2705 Saved!')
$content = $content.Replace(([char]0x2705 + ' DPR Updated!'), '\u2705 DPR Updated!')
$content = $content.Replace(([char]0x2705 + ' All synced!'), '\u2705 All synced!')
$content = $content.Replace(([char]0x2705 + ' DPR Generated!'), '\u2705 DPR Generated!')
$content = $content.Replace(([char]0x2705 + ' User created successfully!'), '\u2705 User created successfully!')
$content = $content.Replace(([char]0x2705 + ' User deleted!'), '\u2705 User deleted!')
$content = $content.Replace(([char]0x2705 + ' Password updated!'), '\u2705 Password updated!')
$content = $content.Replace(([char]0x2705 + ' Project added!'), '\u2705 Project added!')
$content = $content.Replace(([char]0x2705 + ' Activated'), '\u2705 Activated')
$content = $content.Replace(([char]0x2705 + ' Deactivated'), '\u2705 Deactivated')
$content = $content.Replace(([char]0x2705 + ' Project renamed!'), '\u2705 Project renamed!')
$content = $content.Replace(([char]0x2705 + ' Deleted project and child dependencies!'), '\u2705 Deleted project and child dependencies!')
$content = $content.Replace(([char]0x2705 + ' Deleted activity and child dependencies!'), '\u2705 Deleted activity and child dependencies!')
$content = $content.Replace(([char]0x2705 + ' Activity renamed!'), '\u2705 Activity renamed!')
$content = $content.Replace(([char]0x2705 + ' Edit access granted!'), '\u2705 Edit access granted!')
$content = $content.Replace(([char]0x2705 + ' Request sent!'), '\u2705 Request sent!')
$content = $content.Replace(([char]0x2705 + ' No pending requests.'), '\u2705 No pending requests.')
$content = $content.Replace(((getEmoji 0x1F9F9) + ' Clean Corrupted Rows'), '\uD83E\uDDF9 Clean Corrupted Rows')
$content = $content.Replace((getEmoji 0x1F465) + ' All Users', '\uD83D\uDC65 All Users')
$content = $content.Replace(((getEmoji 0x1F512) + ' Edit window expired. Request Edit first.'), '\uD83D\uDD12 Edit window expired. Request Edit first.')
$content = $content.Replace((([char]0x270F + [char]0xFE0F) + ' Edit'), '\u270F\uFE0F Edit')
$content = $content.Replace((([char]0x270F + [char]0xFE0F) + ' Edit (Disabled)'), '\u270F\uFE0F Edit (Disabled)')
$content = $content.Replace((([char]0x270F + [char]0xFE0F) + ' Loaded for editing " + [char]0x2014 + " click Generate DPR when done'), '\u270F\uFE0F Loaded for editing \u2014 click Generate DPR when done')
$content = $content.Replace([string]([char]0x270F + [char]0xFE0F), '\u270F\uFE0F')
$content = $content.Replace((getEmoji 0x1F5D1), '\uD83D\uDDD1\uFE0F')
$content = $content.Replace((getEmoji 0x1F7E2), '\uD83D\uDFE2')
$content = $content.Replace((getEmoji 0x1F534), '\uD83D\uDD34')
$content = $content.Replace((getEmoji 0x1F4CD), '\uD83D\uDCCD')
$content = $content.Replace((getEmoji 0x1F528), '\uD83D\uDD28')
$content = $content.Replace((getEmoji 0x1F4CC), '\uD83D\uDCCC')
$content = $content.Replace((getEmoji 0x1F4E6), '\uD83D\uDCE6')
$content = $content.Replace((getEmoji 0x1F4C5), '\uD83D\uDCC5')
$content = $content.Replace((getEmoji 0x1F464), '\uD83D\uDC64')
$content = $content.Replace((getEmoji 0x1F477), '\uD83D\uDC77')
$content = $content.Replace((getEmoji 0x1F4C4), '\uD83D\uDCC4')
$content = $content.Replace((getEmoji 0x1F4F7), '\uD83D\uDCF7')
$content = $content.Replace((getEmoji 0x1F4F8), '\uD83D\uDCF8')
$content = $content.Replace((getEmoji 0x1F504), '\uD83D\uDD04')
$content = $content.Replace((getEmoji 0x1F4AC), '\uD83D\uDCAC')
$content = $content.Replace((getEmoji 0x1F4CB), '\uD83D\uDCCB')
$content = $content.Replace((getEmoji 0x1F4CA), '\uD83D\uDCCA')
$content = $content.Replace(([char]0x2699 + [char]0xFE0F), '\u2699\uFE0F')
$content = $content.Replace((getEmoji 0x1F511), '\uD83D\uDD11')
$content = $content.Replace([string]([char]0x25C0), '\u25C0')
$content = $content.Replace([string]([char]0x25B6), '\u25B6')

# 5. Emojis inside JS dynamically rendered template strings (for project/activity lists & admin panel)
$content = $content.Replace(((getEmoji 0x1F4CD) + ' ${proj.project_name}'), '&#128205; ${proj.project_name}')
$content = $content.Replace(('${act ? ''' + (getEmoji 0x1F7E2) + ''' : ''' + (getEmoji 0x1F534) + '''}'), '${act ? ''&#128994;'' : ''&#128308;''}')
$content = $content.Replace(('${act ? ''' + (getEmoji 0x1F534) + ' Off'' : ''' + (getEmoji 0x1F7E2) + ' On''}'), '${act ? ''&#128308; Off'' : ''&#128994; On''}')
$content = $content.Replace(('${s.status === ''active'' ? ''' + (getEmoji 0x1F534) + ''' : ''' + (getEmoji 0x1F7E2) + '''}'), '${s.status === ''active'' ? ''&#128308;'' : ''&#128994;''}')
$content = $content.Replace(((getEmoji 0x1F528) + ' ${main.activity_name}'), '&#128296; ${main.activity_name}')
$content = $content.Replace(((getEmoji 0x1F464) + ' ${u.username}'), '&#128100; ${u.username}')
$content = $content.Replace(('<span style="background:#fee2e2;color:#ef4444;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;margin-left:6px;display:inline-block;">' + [char]0x26A0 + [char]0xFE0F + ' Inactive</span>'), '<span style="background:#fee2e2;color:#ef4444;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;margin-left:6px;display:inline-block;">&#9888;&#65039; Inactive</span>')
$content = $content.Replace(('<span style="background:#dcfce7;color:#10b981;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;margin-left:6px;display:inline-block;">' + (getEmoji 0x1F7E2) + ' Active</span>'), '<span style="background:#dcfce7;color:#10b981;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;margin-left:6px;display:inline-block;">&#128994; Active</span>')
$content = $content.Replace(('>' + [char]0x270F + [char]0xFE0F + '</button>'), '>&#9999;&#65039;</button>')
$content = $content.Replace(('>' + (getEmoji 0x1F5D1) + '</button>'), '>&#128465;&#65039;</button>')
$content = $content.Replace(('title="Reset Password">' + (getEmoji 0x1F511) + '</button>'), 'title="Reset Password">&#128273;</button>')
$content = $content.Replace(('title="Delete User">' + (getEmoji 0x1F5D1) + '</button>'), 'title="Delete User">&#128465;&#65039;</button>')
$content = $content.Replace(('>' + (getEmoji 0x1F464) + ' '), '>&#128100; ')

# Emojis inside JS strings that render inside custom reports
$content = $content.Replace(((getEmoji 0x1F4C5) + ' Date :'), '\uD83D\uDCC5 Date :')
$content = $content.Replace(((getEmoji 0x1F4CD) + ' Site :'), '\uD83D\uDCCD Site :')
$content = $content.Replace(((getEmoji 0x1F464) + ' Filled by :'), '\uD83D\uDC64 Filled by :')
$content = $content.Replace(((getEmoji 0x1F477) + ' Total :'), '\uD83D\uDC77 Total :')
$content = $content.Replace(((getEmoji 0x1F477) + ' Total Manpower :'), '\uD83D\uDC77 Total Manpower :')
$content = $content.Replace(((getEmoji 0x1F528) + ' ${title}'), '\uD83D\uDD28 ${title}')
$content = $content.Replace(((getEmoji 0x1F4CC) + ' ${r.note}'), '\uD83D\uDCCC ${r.note}')
$content = $content.Replace(((getEmoji 0x1F4E6) + ' ${toTitleCase(main)}'), '\uD83D\uDCE6 ${toTitleCase(main)}')
$content = $content.Replace(((getEmoji 0x1F4CD) + ' ${getSiteDisplayName(item.site)}'), '\uD83D\uDCCD ${getSiteDisplayName(item.site)}')
$content = $content.Replace(('${actHint ? `&nbsp;·&nbsp; ' + (getEmoji 0x1F4CB) + ' ${actHint}` : ''}'), '${actHint ? `&nbsp;·&nbsp; \uD83D\uDCCB ${actHint}` : ''}')
$content = $content.Replace(((getEmoji 0x1F4C5) + ' ${formatDate(d) || ''—''}'), '\uD83D\uDCC5 ${formatDate(d) || ''\u2014''}')
$content = $content.Replace(((getEmoji 0x1F4C5) + ' ${formatDate(toYMD(item.date))}'), '\uD83D\uDCC5 ${formatDate(toYMD(item.date))}')

# 6. Clean up mangled comment boundaries
$mangled_comment_dash = [string][char[]]@(226, 8221, 8364)
$content = $content.Replace($mangled_comment_dash, [string]([char]0x2014))

[System.IO.File]::WriteAllText($filePath, $content, $utf8)
Write-Host "Replacement completed successfully."
