-- ════════════════════════════════════════════════════════════════
-- 007 — Contractors and their site allocation
--
-- Additive and safe to re-run. Apply BEFORE deploying the code that uses
-- it. Until then the app still works, but no contractors are listed and
-- manpower rows can't carry a contractor.
--
--   contractors          the master list, managed in Admin › Contractors
--   site_contractors     which sites a contractor works on. Allocating a
--                        parent site covers all of its sub-sites, the same
--                        rule as user_sites (006).
--   dpr_manpower_entries.contractor
--                        the contractor tagged on a manpower line. Stored as
--                        the name at the time (like material_logs.contractor),
--                        so a later rename or delete never rewrites a filed
--                        report.
-- ════════════════════════════════════════════════════════════════

create table if not exists contractors (
  id          bigint generated by default as identity primary key,
  name        text not null,
  phone       text,
  trade       text,                 -- e.g. Civil, Electrical, Plumbing (free text)
  status      text not null default 'active' check (status in ('active', 'inactive')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists idx_contractors_name on contractors (lower(name));

drop trigger if exists trg_contractors_updated_at on contractors;
create trigger trg_contractors_updated_at
  before update on contractors
  for each row execute function set_updated_at();

create table if not exists site_contractors (
  contractor_id bigint not null references contractors (id) on delete cascade,
  project_id    bigint not null references projects (id) on delete cascade,
  created_at    timestamptz not null default now(),
  primary key (contractor_id, project_id)
);
create index if not exists idx_site_contractors_project_id on site_contractors (project_id);

alter table dpr_manpower_entries
  add column if not exists contractor text;

-- Seed the master list from contractor names already typed into consumption
-- entries, so existing names show up in Admin › Contractors to allocate.
insert into contractors (name)
select distinct on (lower(trim(contractor))) trim(contractor)
from material_logs
where contractor is not null and trim(contractor) <> ''
order by lower(trim(contractor)), trim(contractor)
on conflict do nothing;
